version: '3.8'

services:
  webapi:
    container_name: products_crud_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStrong(!)Password
    ports:
      - "1433:1433"
    volumes:
      - sql-server-data:/var/opt/mssql

volumes:
  sql-server-data:
    name: sql-data
